[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
dev_mode = reload,xml
admin_passwd = $pbkdf2-sha512$600000$kBICgLDW.n/vPQegdK51Tg$/TTvCg8tpCsAQktA7fKRM56DfXfmcnWIPQ1JErNqPxMb3U.Nlgr1DEEkyyMH/qfpnfZtmP991RCGkNZ7tFfj.w

